core/urls.py
from django.conf import settings
from django.urls import include, path
from django.contrib import admin
from django.conf.urls.static import static

from wagtail.admin import urls as wagtailadmin_urls
from wagtail import urls as wagtail_urls
from wagtail.documents import urls as wagtaildocs_urls

from apps.search import views as search_views
from apps.home import views as home_views

urlpatterns = [
    path("django-admin/", admin.site.urls),
    path("admin/", include(wagtailadmin_urls)),
    path("documents/", include(wagtaildocs_urls)),
    path("search/", search_views.search, name="search"),
    path("sitemap/", home_views.sitemap, name="sitemap"),
]

if settings.DEBUG:
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    urlpatterns += staticfiles_urlpatterns()

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += [path("", include(wagtail_urls))]

apps/agenda/models.py
from django.core.exceptions import ValidationError
from wagtail.models import Page
from django.db import models
from wagtail.admin.panels import FieldPanel
from django.core.paginator import Paginator
from django.utils import timezone

from apps.common.models import DetailPage, BasePage


def get_events(date_filter, sort_by, villes=None):
    events = EventPage.objects.live().filter(date_filter)
    if villes:
        ville_list = villes.split(',')
        if len(ville_list) == 2:  # Si les deux villes sont sélectionnées
            events = events.filter(models.Q(ville__in=ville_list) | models.Q(ville=EventPage.BOTH))
        else:
            events = events.filter(models.Q(ville=ville_list[0]) | models.Q(ville=EventPage.BOTH))
    return events.order_by(sort_by, 'title')

def get_future_events(limit=5):
    return EventPage.objects.live().filter(start_date__gte=timezone.now()).order_by('start_date')[:limit]


class EventListPage(BasePage):
    intro = models.TextField(blank=True)
    content_panels = BasePage.content_panels + [FieldPanel('intro')]

    def get_events_context(self, request, date_filter, default_sort):
        context = {}
        sort_by = request.GET.get('sort_by', default_sort)
        villes = request.GET.get('ville', '')
        search_query = request.GET.get('search', '')
        events = get_events(date_filter, sort_by, villes)
    
        if search_query:
            events = events.filter(title__icontains=search_query)
    
        paginator = Paginator(events, 9)
        context['sort_by'] = sort_by
        context['villes'] = villes.split(',') if villes else []
        context['search_query'] = search_query
        return context, paginator

    class Meta:
        abstract = True

class AgendaIndexPage(EventListPage):
    def get_context(self, request, *args, **kwargs):
        context = super().get_context(request, *args, **kwargs)
        events_context, paginator = self.get_events_context(
            request, 
            models.Q(start_date__gte=timezone.now()),
            'start_date'
        )
        context.update(events_context)
        context['upcoming_events'] = paginator.get_page(request.GET.get('page'))
        context['past_events_page'] = self.get_children().type(PastEventsPage).live().first()
        return context

    class Meta:
        verbose_name = "Page Agenda"

class PastEventsPage(EventListPage):
    def get_context(self, request, *args, **kwargs):
        context = super().get_context(request, *args, **kwargs)
        events_context, paginator = self.get_events_context(
            request, 
            models.Q(start_date__lt=timezone.now()),
            '-start_date'
        )
        context.update(events_context)
        context['past_events'] = paginator.get_page(request.GET.get('page'))
        return context

    class Meta:
        verbose_name = "Événements passés"


class EventPage(DetailPage):
    MAUGUIO = 'Mauguio'
    CARNON = 'Carnon'
    BOTH = 'Les deux'
    VILLE_CHOICES = [
        (MAUGUIO, 'Mauguio'),
        (CARNON, 'Carnon'),
        (BOTH, 'Mauguio et Carnon'),
    ]

    start_date = models.DateField(
        "Date de début",
        help_text="Date de début de l'événement",
        default=timezone.now
    )
    end_date = models.DateField(
        "Date de fin",
        blank=True,
        null=True,
        help_text="Date de fin de l'événement (laisser vide si l'événement dure un seul jour)"
    )
    ville = models.CharField(
        max_length=10,
        choices=VILLE_CHOICES,
        default=MAUGUIO,
    )

    content_panels = DetailPage.content_panels + [
        FieldPanel('start_date'),
        FieldPanel('end_date'),
        FieldPanel('ville'),
    ]

    def clean(self):
        if self.end_date and self.end_date < self.start_date:
            raise ValidationError("La date de fin ne peut pas être antérieure à la date de début.")

    class Meta:
        verbose_name = "Événement"

apps/agenda/templates/agenda/includes/event_card.html
{% load wagtailcore_tags wagtailimages_tags %}

<article class="group bg-white rounded-xl shadow-md hover:shadow-xl transition-all duration-300 overflow-hidden h-full flex flex-col hover:scale-[1.03] cursor-pointer"
    onclick="window.location.href='{{ event.url }}'">
    <div class="relative overflow-hidden h-56 bg-gray-200 text-light-text">
        {% if section_class == "past-events" %}
            <div class="absolute z-10 w-full bg-gray-500/90 text-center px-4 py-1 tracking-widest">
                Passé
            </div>
        {% endif %}
        {% if event.image %}
            {% image event.image fill-400x300 as event_img %}
            <img src="{{ event_img.url }}" alt="{{ event.title }}" class="w-full h-56 object-cover">
        {% else %}
            <div class="flex items-center justify-center h-full">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" class="size-20 text-gray-400">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z"></path>
                </svg>
            </div>
        {% endif %}
        <div class="absolute bottom-0 left-0 right-0 bg-gradient-to-t from-black/40 to-transparent h-24"></div>
        <time class="absolute bottom-4 left-4 font-medium px-3 py-1 bg-secondary/80 rounded-full text-sm">
            {{ event.start_date|date:"d M Y" }}{% if event.end_date %} - {{ event.end_date|date:"d M" }}{% endif %}
        </time>
        <div class="absolute bottom-4 right-4 font-medium px-3 py-1 bg-secondary/80 rounded-full text-sm">
            {{ event.get_ville_display }}
        </div>
    </div>
    <div class="p-6 flex flex-col flex-grow h-auto">
        <div class="flex-grow">
            <h3 class="text-xl font-bold mb-2 group-hover:text-dark-text transition-colors">
                {{ event.title }}
            </h3>
            <div class="text-dark-text/60 line-clamp-3">
                {{ event.subtitle|default:event.content|richtext|striptags|truncatewords:20 }}
            </div>
        </div>
        <a href="{{ event.url }}" class="btn-outline mt-2 relative overflow-hidden group-hover:text-white! group-hover:border-secondary!">
            <span class="absolute inset-0 bg-secondary transition-transform duration-300 transform -translate-x-full group-hover:translate-x-0"></span>
            <span class="relative z-10">En savoir plus</span>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" class="w-5 h-5 relative z-10">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 8l4 4m0 0l-4 4m4-4H3"></path>
            </svg>
        </a>
    </div>
</article>

apps/agenda/templates/agenda/includes/sort_filter_buttons.html
{% load wagtailcore_tags %}

<div class="mb-4 flex flex-wrap items-center justify-center md:justify-evenly gap-4 lg:gap-8 text-dark-text">
    <div>
        <label for="sort_by" class="mr-2">Trier par :</label>
        <select id="sort_by" name="sort_by" onchange="updateURLParameter('sort_by', this.value);" class="p-2 pl-4 rounded-xl border">
            <option value="date" {% if sort_by == 'date' %}selected{% endif %}>Date</option>
            <option value="title" {% if sort_by == 'title' %}selected{% endif %}>Titre</option>
        </select>
    </div>
    <div class="flex gap-2 flex-wrap">
        <button onclick="toggleVille('Mauguio');" class="btn btn-outline {% if 'Mauguio' in villes %}active{% endif %}">Mauguio</button>
        <button onclick="toggleVille('Carnon');" class="btn btn-outline {% if 'Carnon' in villes %}active{% endif %}">Carnon</button>
    </div>
    <label for="search"></label><input type="text" id="search" name="search" placeholder="Recherche" value="{{ search_query }}" onkeydown="if (event.key === 'Enter') updateURLParameter('search', this.value);" class="ml-4 p-2 border rounded-xl w-full lg:w-1/2">
</div>